services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://its-manager:progettoits2026@mysql-its-manager.alwaysdata.net:3306/its-manager_db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
